- app/controllers/users_controller.rb
- app/views/matches/show.html.erb
- app/views/shared/_navbar.html.erb
- app/views/users/show.html.erb
- config/routes.rb
I created a Profile page & link to profile of player in show
> Profile page & link to profile of player in show

- app/assets/stylesheets/pages/_profile.scss
- app/views/users/show.html.erb
small style change in profile page
> small sytle change

- app/assets/stylesheets/components/_card.scss
- app/controllers/users_controller.rb
- app/views/shared/_navbar.html.erb
- app/views/users/index.html.erb
1. link to the page from the navbar
2. ordered desc. list with cards
3. basic styling
> created ranking page mvp

- app/assets/stylesheets/components/_chatroom.scss
- app/channels/chatroom_channel.rb
- app/controllers/matches_controller.rb
- app/controllers/messages_controller.rb
- app/javascript/controllers/chatroom_subscription_controller.js
- app/models/chatroom.rb
- app/models/match.rb
- app/models/message.rb
- app/views/matches/show.html.erb
- config/routes.rb
- db/migrate/20211129151951_add_match_ref_to_chatrooms.rb
- db/migrate/20211129155302_add_match_to_messages.rb
- db/migrate/20211129165151_remove_chatroom_references_from_messages.rb
- db/schema.rb
> Matchchatroom

- app/models/match.rb
1. presence :true for all input fields except comment
2. length: { minimum: 10 } for the comment
> update validations for matches table

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_form.scss
- app/assets/stylesheets/config/_colors.scss
- app/javascript/controllers/select2_controller.js
- app/models/match.rb
- app/views/matches/new.html.erb
- db/seeds.rb
- package.json
- yarn.lock
1. autocomplete search is implemented
2. validations updated & fixed
3. hints are displayed when user's input doesn't pass validations
> venue search function in match create forme

- app/assets/stylesheets/components/_map.scss
- app/assets/stylesheets/config/_fonts.scss
- app/javascript/packs/gilder.js
- app/views/layouts/application.html.erb
- app/views/matches/_info_window.html.erb
- app/views/users/show.html.erb
> Map cards displayed

- app/assets/stylesheets/components/_modal.scss
- app/views/matches/index.html.erb
> styled modal

- app/controllers/matches_controller.rb
- app/views/matches/show.html.erb
- app/views/users/show.html.erb
> Lastmatchesclick

- app/assets/stylesheets/components/_avatar.scss
- app/assets/stylesheets/components/_card.scss
- app/views/users/index.html.erb
> Stylerankingpage

- app/assets/stylesheets/components/_button.scss
- app/assets/stylesheets/components/_container.scss
- app/assets/stylesheets/config/_colors.scss
- app/assets/stylesheets/pages/_profile.scss
- app/views/matches/index.html.erb
- app/views/reviews/new.html.erb
- app/views/users/show.html.erb
I added styling to the profile page & created a link from the profile page to the ranking page & styled the inactive buttons
> Lastmatchesprofile

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_form.scss
- app/javascript/components/flatpickr.js
- app/javascript/packs/application.js
- app/models/match.rb
- app/views/layouts/application.html.erb
- app/views/matches/new.html.erb
1. date displayed in a user-friendly format
2. past dates disabled
> disable past dates and other minor fixes

- app/assets/stylesheets/components/_avatar.scss
- app/assets/stylesheets/components/_card.scss
- app/assets/stylesheets/components/_container.scss
- app/assets/stylesheets/components/_modal.scss
- app/views/layouts/application.html.erb
- app/views/matches/mymatches.html.erb
fixed backgroundcolor
changed mymatches
> containerbackground and cards

- app/assets/stylesheets/components/_avatar.scss
- app/assets/stylesheets/components/_button.scss
- app/assets/stylesheets/components/_map.scss
- app/assets/stylesheets/pages/_home.scss
- app/assets/stylesheets/pages/_show.scss
- app/views/matches/show.html.erb
- app/views/users/show.html.erb
I added different styling things in the show page
> Homepageandsvg

- app/assets/stylesheets/components/_card.scss
- app/views/matches/mymatches.html.erb
> fixed content mymatch

- app/assets/stylesheets/pages/_profile.scss
- app/views/matches/index.html.erb
- app/views/matches/mymatches.html.erb
- app/views/users/show.html.erb
> i dont know what it was about

- app/views/matches/mymatches.html.erb
pending matches is new default on my matches
> pending matches is new default on my matches

- app/views/matches/_match_search.html.erb
- app/views/matches/index.html.erb
- app/views/matches/mymatches.html.erb
- app/views/matches/new.html.erb
- app/views/pages/home.html.erb
- app/views/users/index.html.erb
- app/views/users/show.html.erb
- public/404.html
- public/500.html
> changed match to fliq

- app/assets/stylesheets/components/_form.scss
> changed font color

- public/404.html
- public/500.html
> deleted class

- app/assets/stylesheets/pages/_home.scss
- app/views/matches/_match_search.html.erb
- app/views/pages/home.html.erb
> centered homepagecontent

- app/assets/stylesheets/pages/_home.scss
- app/views/matches/_match_search.html.erb
- app/views/pages/home.html.erb
> uncentered
